server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ =404;
  }

  location /_astro/ {
    try_files $uri =404;
    access_log off;
    expires 1y;
    add_header Cache-Control "public, immutable";
  }

  location ~* \.(?:avif|css|gif|ico|jpeg|jpg|js|mjs|png|svg|webp|woff|woff2)$ {
    try_files $uri =404;
    access_log off;
    expires 30d;
    add_header Cache-Control "public";
  }
}
